spring:
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#            add-to-simple-url-handler-mapping: true
#            corsConfigurations:
#              '[/**]':
#                allowedOrigins: "http://localhost:4200"
#                allowedHeaders:
#                  - "Origin"
#                  - "Content-Type"
#                  - "Accept"
#                  - "Authorization"
#                  - "Referer"
#                allowedMethods:
#                  - POST
#                  - GET
#                  - OPTIONS
#                  - DELETE
#                  - PUT
#                  - PATCH
#                  - HEAD


      discovery:
        locator:
          enabled: true
      routes:
        - id : auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: post-service
          uri: lb:http://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**

        - id: chat-service
          uri: lb:http://CHAT-SERVICE
          predicates:
            - Path=/stomp-endpoint/**
          filters:
              - RemoveResponseHeader=Sec-WebSocket-Protocol

        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**

        - id: like-service
          uri: lb:http://LIKE-SERVICE
          predicates:
            - Path=/api/v1/likes/**

        - id: friendship-service
          uri: lb:http://FRIENDSHIP-SERVICE
          predicates:
            - Path=/api/v1/friendships/**
server:
  port: 8589
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782D413D4428472B4B6250645367566B970
      expiration: 86400000