spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**

        - id: post-service
          uri: lb:http://POST-SERVICE
          predicates:
            - Path=/api/v1/posts/**

        - id: chat-service
          uri: lb:http://CHAT-SERVICE
          predicates:
            - Path=/stomp-endpoint/**
          filters:
              - RemoveResponseHeader=Sec-WebSocket-Protocol

        - id: comment-service
          uri: lb:http://COMMENT-SERVICE
          predicates:
            - Path=/api/v1/comments/**

        - id: like-service
          uri: lb:http://LIKE-SERVICE
          predicates:
            - Path=/api/v1/likes/**
server:
  port: 8589