spring:
  datasource:
    # URL of the PostgreSQL database
    url: jdbc:postgresql://localhost:5432/notificationservicedb
    # Username for the database connection
    username: postgres
    # Password for the database connection
    password: postgres
    # Driver class name for PostgreSQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # Type of database
    database: postgresql
    # Hibernate dialect for PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notificationGroup , websocketGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        #since we want to serialize a json object, the producer needs to inform the consumer of our topic
        #what is the object that we are sending so here we are sending an object of type orderConfirmation
        spring.json.type.mapping: message:org.example.notificationservice.kafka.consumer.AuthenticationMessage,notification:org.example.notificationservice.kafka.consumer.NotificationDTO
